workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID               # Execute jobs in merge request context
    - if: $CI_COMMIT_BRANCH == 'master'      # Execute jobs when a new commit is pushed to master branch

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - sudo docker build -t talpibot-bot:$CI_COMMIT_SHORT_SHA

test and cleanup:
  stage: test
  needs:
    - build
  script:
    - sudo docker run --rm talpibot-bot:$CI_COMMIT_SHORT_SHA python -m unittest
  after_script:
    - sudo docker image prune -f
    - sudo docker rmi talpibot-bot:$CI_COMMIT_SHORT_SHA
  except:
    - master

test:
  stage: test
  needs:
    - build
  script:
    - sudo docker run --rm talpibot-bot:$CI_COMMIT_SHORT_SHA python -m unittest
  only:
    - master

deploy:
  stage: deploy
  needs:
    - test
  script:
    - sudo docker tag talpibot-bot:$CI_COMMIT_SHORT_SHA talpibot-bot:latest
    - sudo docker rmi talpibot-bot:$CI_COMMIT_SHORT_SHA
    - sudo systemctl restart talpibot-bot
  after_script:
    - sudo docker image prune -f
  only:
  - master
